---
- name: set locale
  hosts: all
  become: yes

  tasks:
    - name: add locale to profile
      blockinfile:
        path: /etc/profile
        block: |
          export LC_ALL=en_US.UTF-8
          export LC_CTYPE=en_US.UTF-8
