---
- name: Installing Zabbix
  hosts: all
  become: yes

  tasks:
    - name: setup zabbix repository
      yum:
        name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
        state: present


    - name: Install zabbix
      yum:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-agent 
        state: present

    - name: Modify config file
      lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: ^# php_value date.timezone Europe/Riga
        line: 'php_value date.timezone Asia/Shanghai'
        backup: yes

    - name: Modify config file
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: ^# DBPassword=
        line: 'DBPassword=vagrant'
        backup: yes

    - name: disable Selinux
      selinux:
        state: disabled

    - name: disable selinux runtime
      command: setenforce 0

    - name: Start zabbix service
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - zabbix-server
        - zabbix-agent
        - httpd


    - name: restore backup database
      shell: mysql zabbix < /vagrant/zabbix.sql

